<div id="container_41df46e">
  <div class="textstyle1">
<h1 id="heading_48fac406" ><span id="heading_48fac406_padding" >Epic Learning  <br/></span></h1>    <span class="textstyle2"><br/><br/></span>
    <div id="container_6f123cbb">
      <div id="container_6f123cbb_padding" >
        <div class="textstyle1">
          <div id="container_52c2f018">
            <div id="container_52c2f018_padding" >
              <div class="textstyle1">
<span class="textstyle3">Use training login IDs from table below to access the eNews and Learning Library links (Password: train)</span><span class="textstyle4"><a href="https://bsmh.ancileuperform.com/#/folder/enews?authMode=cf6e9267-b303-496d-a3e1-4aa0f8ea54a7" target="_blank" class="wsp2aa5a736"><br/>eNews</a></span><span class="textstyle5"><br/></span><span class="textstyle4"><a href="https://bsmh.ancileuperform.com/#/project/epic?authMode=cf6e9267-b303-496d-a3e1-4aa0f8ea54a7" target="_blank" class="wsp2aa5a736">Learning Library</a></span>                <span class="textstyle6"> <br/><br/></span>
                <img src="rc_images/textanim_fklu3.gif" width="1295" height="62" id="img_2fd91754" alt="" title="" />
                <span class="textstyle7"><br/>Registration Navigators Are Coming in August. Please click </span>
                <span class="textstyle8"><a href="https://bsmh.ancileuperform.com/#/content/1.11.246058?authMode=cf6e9267-b303-496d-a3e1-4aa0f8ea54a7" target="_blank" class="wsp2aa5a736">here</a></span>
                <span class="textstyle7"> for more information.</span>
                <span class="textstyle9"> Note: Use username: &quot;GCPA25&quot; and password: &quot;train&quot; if prompted to login to the Learning Library.</span>
                </div>
              <div style="clear:both"></div>
              </div>
            </div>
          <div id="container_12fa7717">
            <div id="container_12fa7717_padding" >
              <div class="textstyle1">
<span class="textstyle5">Next Training Environment Downtime: <br/></span><span class="textstyle10">Stream 1: 8/25 @ 5:15 - 8/27 for Critical Fix Package</span><span class="textstyle5"><br/></span><span class="textstyle10">Stream 2: 9/15/2023 (Tenative Date)<br/></span><span class="textstyle8"><br/></span>                <table id="table_4aba8bf3" cellpadding="3" cellspacing="1" >
	<tr>
		<td width="50%" height="23px" style="vertical-align: top; overflow:hidden; ">                  <div id="cell_5c87a008">
                    <div class="textstyle1">
                      <span class="textstyle11">Version: Feb2023</span>
                      </div>
                    </div>
		</td>
		<td width="50%" height="23px" style="vertical-align: top; overflow:hidden; ">                  <div id="cell_5c87a008">
                    <div class="textstyle1">
                      <span class="textstyle11">Version: May22</span>
                      </div>
                    </div>
		</td>
	</tr>
	<tr>
		<td width="50%" height="23px" style="vertical-align: top; overflow:hidden; ">                  <div id="cell_5c87a008">
                    <div class="textstyle1">
                      <span class="textstyle11">Stream 1 (New)</span>
                      </div>
                    </div>
		</td>
		<td width="50%" height="23px" style="vertical-align: top; overflow:hidden; ">                  <div id="cell_7e041a8c">
                    <div class="textstyle1">
                      <span class="textstyle11">Stream 2</span>
                      <span class="textstyle7"> </span>
                      <span class="textstyle11">(Current)</span>
                      </div>
                    </div>
		</td>
	</tr>
	<tr>
		<td width="50%" height="23px" style="vertical-align: top; overflow:hidden; ">                  <div id="cell_1c6e0b8e">
                    <div class="textstyle1">
                      <span class="textstyle11">MSTCPNEW</span>
                      </div>
                    </div>
		</td>
		<td width="50%" height="23px" style="vertical-align: top; overflow:hidden; ">                  <div id="cell_614a360">
                    <div class="textstyle1">
                      <span class="textstyle11">MSTCPCUR</span>
                      </div>
                    </div>
		</td>
	</tr>
	<tr>
		<td width="50%" height="23px" style="vertical-align: top; overflow:hidden; ">                  <div id="cell_431e0d1c">
                    <div class="textstyle1">
                      <span class="textstyle11">ACEs 9-16 and SBX</span>
                      </div>
                    </div>
		</td>
		<td width="50%" height="23px" style="vertical-align: top; overflow:hidden; ">                  <div id="cell_3dbc5511">
                    <div class="textstyle1">
                      <span class="textstyle11">ACEs 1-8 and PLY</span>
                      </div>
                    </div>
		</td>
	</tr>
                  </table>
                <span class="textstyle5"><br/><br/></span>
                <div id="text_71fbe97c">
                  <div class="textstyle1">
                    <span class="textstyle4"><a href="environmentassignment.html" class="wsp2aa5a736">Training Environment Assignments</a></span>
                    </div>
                  </div>
                </div>
              <div style="clear:both"></div>
              </div>
            </div>
          <span class="textstyle2"> </span>
          <span class="textstyle2"><br/><br/></span>
          <div id="container_2ccd4f1f">
            <div id="container_2ccd4f1f_padding" >
              <div class="textstyle1">
<span class="textstyle12">Training Login and Class Material Search</span><span class="textstyle13">:</span>                </div>
              </div>
            </div>
          </div>
        <div style="clear:both"></div>
        </div>
      </div>
    </div>
  </div>
